#!/usr/bin/env python
# -*- coding: utf-8 -*-

import re

lower = re.compile(r'^([a-z]|_)*$')
lower_colon = re.compile(r'^([a-z]|_)*:([a-z]|_)*$')
problemchars = re.compile(r'[=\+/&<>;\'"\?%#$@\,\. \t\r\n]')
street_type_re = re.compile(r'(\b\S+\.?$)', re.IGNORECASE)

osm_file_name = "/Users/deke/dev/data/source/da/cape-town_south-africa.osm"
json_file_name = "/Users/deke/dev/data/source/da/cape-town_south-africa.osm.json"


created_keys = [ "version", "changeset", "timestamp", "user", "uid"]

expected_street_type = ["Street", "Avenue", "Boulevard", "Drive", "Court", "Place", "Square", "Lane", "Road", 
            "Trail", "Parkway", "Commons", "Close", "Way", "Circle", "Walk", "Crescent", "North",
            "South","Path","Gardens"]

street_type_mapping = { "St": "Street",
            "St.": "Street",
            "Ave" : "Avenue",
            "Ave." : "Avenue",
            "Rd" : "Road",
            "Rd." : "Road",
            "street" : "Street",
            "avenue" : "Avenue",
            "road" : "Road",
            "Singel" : "Crescent",
            "Straat" : "Street",
            "st" : "Street",
            }

#Tag keys in this dictionary(k,v) where tag.key=k have their keys replaced by tag.key=v
substitute_tags = {
"BEACON" : "beacon",
"date sunk" : "date_sunk", 
"footway:left.smoothness" : "footway:left:smoothness",
"footway:left.surface" : "footway:left:surface",
"footway:left.width" : "footway:left:width",
"footway:right.smoothness" : "footway:right:smoothness",
"footway:right.surface" : "footway:right:surface",
"footway:right.width" : "footway:right:width",
"octane_95" : "fuel:octane_95",
"cellphone" : "phone",
"diesel" : "fuel:diesel",
 }

#Tag keys in this dictionary(k,v) where tag.key="k" have their value pushed down to the value field 
#and the key replaced by v
bump_tags = {
"anglican" : "denomination", 
"butcher" : "shop",
"parachute_jumping" : "sport",
}

#Ignore these tagsi
ignore_tag_list = [
"Cape Peninsula University of Technology",
"FIXME",
"Nyanga",
"South_Africa",
"addr2:street",
"airport_helipad",
"lock",
"firefishy",
"fixme",

  ]


"""
'4wd_only',
 'BEACON',
 'Cape Peninsula University of Technology',
 'CoCT:CLASS',
 'CoCT:ROAD_NO',
 'CoCT:SEGNAME',
 'CoCT:SEG_TYPE',
 'CoCT:SPEED',
 'CoCT:SUFFIX',
 'FIXME',
 'Nyanga',
 'South_Africa',
 'abandoned',
 'abutters',
 'access',
 'access:conditional',
 'addr2:street',
 'addr:city',
 'addr:country',
 'addr:flats',
 'addr:housename',
 'addr:housenumber',
 'addr:inclusion',
 'addr:interpolation',
 'addr:name',
 'addr:place',
 'addr:postcode',
 'addr:province',
 'addr:street',
 'addr:suburb',
 'addr:unit',
 'admin_level',
 'aerialway',
 'aerodrome',
 'aeroway',
 'airport_helipad',
 'alcohol',
 'ale',
 'alt',
 'alt_name',
 'alt_name:de',
 'alt_name:en',
 'amenity',
 'anglican',
 'area',
 'area:highway',
 'artist_name',
 'atm',
 'attraction',
 'avalanche_protector:open',
 'backrest',
 'barrier',
 'beacon:type',
 'bench',
 'bicycle',
 'board_type',
 'boat',
 'border_type',
 'boundary',
 'braai',
 'brand',
 'bridge',
 'bridge:movable',
 'building',
 'building:levels',
 'building:roof',
 'building:structure',
 'building:type',
 'buildingpart',
 'bus',
 'bus_routes',
 'butcher',
 'cables',
 'capacity',
 'capacity:disabled',
 'capacity:parent',
 'capacity:women',
 'capital',
 'capital:legislative',
 'car_wash',
 'caravans',
 'cargo',
 'cars',
 'cellphone',
 'circuit',
 'circuits',
 'climbing',
 'club',
 'coffee',
 'colour',
 'constructed',
 'construction',
 'contact:email',
 'contact:facebook',
 'contact:fax',
 'contact:google_plus',
 'contact:phone',
 'contact:twitter',
 'contact:website',
 'country',
 'covered',
 'craft',
 'crane:note',
 'crane:type',
 'created_by',
 'crossing',
 'crossing_ref',
 'cuisine',
 'cutting',
 'cycle',
 'cycleway',
 'cycleway:left',
 'date sunk',
 'delivery',
 'demolished',
 'demolished:building',
 'demolished:name',
 'denomination',
 'description',
 'designation',
 'destination',
 'destination:backward',
 'destination:forward',
 'destination:lanes',
 'diesel',
 'diet:vegetarian',
 'diplomatic',
 'direction',
 'disabled',
 'dispensing',
 'disused',
 'disused:amenity',
 'disused:generator:source',
 'disused:highway',
 'disused:power',
 'disused:religion',
 'dme',
 'door',
 'drinking_water',
 'drive_through',
 'duration',
 'ele',
 'electrified',
 'email',
 'embankment',
 'emergency',
 'emergency_phone',
 'entrance',
 'ess',
 'exit_to',
 'facebook',
 'fax',
 'fee',
 'fence_type',
 'fire_hydrant:position',
 'fire_hydrant:type',
 'firefishy',
 'fixme',
 'floating',
 'food',
 'foot',
 'footway',
 'footway:left.smoothness',
 'footway:left.surface',
 'footway:left.width',
 'footway:right.smoothness',
 'footway:right.surface',
 'footway:right.width',
 'ford',
 'frequency',
 'fuel:HGV_diesel',
 'fuel:diesel',
 'fuel:octane_80',
 'fuel:octane_95',
 'gauge',
 'generator:manufacturer',
 'generator:method',
 'generator:output:electricity',
 'generator:source',
 'generator:type',
 'goods',
 'halal',
 'heading',
 'height',
 'helipad',
 'hgv',
 'highway',
 'hiking',
 'hires',
 'hires:checkdate',
 'hires:imagery',
 'historic',
 'history',
 'horse',
 'iata',
 'icao',
 'ifr',
 'image',
 'incline',
 'indoor',
 'industrial',
 'information',
 'int_name',
 'internet',
 'internet_access',
 'internet_access:fee',
 'is_in',
 'is_in:continent',
 'is_in:country',
 'is_in:country_code',
 'is_in:state',
 'isced:level',
 'junction',
 'key',
 'landuse',
 'lanes',
 'layer',
 'leaf_type',
 'leisure',
 'length',
 'level',
 'levels',
 'licensed:sacaa',
 'line',
 'link',
 'lit',
 'location',
 'lock',
 'man_made',
 'map_size',
 'map_type',
 'material',
 'maxheight',
 'maxspeed',
 'maxspeed:backward',
 'maxspeed:forward',
 'maxweight',
 'maxwidth',
 'microbrewery',
 'military',
 'mobile',
 'mooring',
 'motor_vehicle',
 'motorcar',
 'motorcycle',
 'motorroad',
 'mountain_pass',
 'mtb',
 'mtb:name',
 'mtb:scale',
 'mtb:scale:uphill',
 'multipolygon',
 'name',
 'name:',
 'name:af',
 'name:ak',
 'name:alt',
 'name:ar',
 'name:cs',
 'name:da',
 'name:de',
 'name:en',
 'name:eo',
 'name:es',
 'name:fi',
 'name:fr',
 'name:he',
 'name:hu',
 'name:is',
 'name:it',
 'name:ja',
 'name:kn',
 'name:la',
 'name:lb',
 'name:lt',
 'name:maybe',
 'name:nl',
 'name:old',
 'name:pl',
 'name:pt',
 'name:ro',
 'name:ru',
 'name:sk',
 'name:sr',
 'name:sv',
 'name:xh',
 'name:zh',
 'national_key_point',
 'natural',
 'navigationaid',
 'noexit',
 'non_real_family',
 'noname',
 'note',
 'nudism',
 'octane_95',
 'odbl',
 'office',
 'old_name',
 'oneway',
 'oneway:conditional',
 'opened',
 'openfire',
 'opening_hours',
 'operator',
 'organisation:type',
 'osmarender:nameDirection',
 'osmarender:renderName',
 'outdoor_seating',
 'owner',
 'parachute_jumping',
 'park',
 'park_ride',
 'parking',
 'parking:condition:both',
 'parking:condition:both:capacity',
 'parking:lane:both',
 'payment:account_cards',
 'payment:bitcoin',
 'payment:cash',
 'payment:coins',
 'payment:credit_cards',
 'payment:debit_cards',
 'payment:litecoin',
 'payment:maestro',
 'payment:notes',
 'payment:telephone_cards',
 'payment:visa',
 'pedestrian',
 'phone',
 'place',
 'plant:output:electricity',
 'pool_table',
 'pool_tables',
 'population',
 'position:accuracy',
 'postal_code',
 'power',
 'power_supply',
 'proposed',
 'protect_class',
 'psv',
 'public_transport',
 'railway',
 'ramp',
 'rank',
 'recycling:cans',
 'recycling:cardboard',
 'recycling:glass',
 'recycling:glass_bottles',
 'recycling:green_waste',
 'recycling:magazines',
 'recycling:newspaper',
 'recycling:paper',
 'recycling:plastic',
 'recycling:plastic_bottles',
 'recycling:plastic_packaging',
 'recycling_type',
 'ref',
 'ref:AEFE',
 'reg_ref',
 'religion',
 'reservoir_type',
 'restriction',
 'role',
 'room',
 'rooms',
 'route',
 'route_ref',
 'ruins',
 'sac_scale',
 'sac_scale_ref',
 'sagns_id',
 'sahra',
 'school',
 'seamark:beacon_lateral:category',
 'seamark:beacon_lateral:colour',
 'seamark:beacon_lateral:shape',
 'seamark:beacon_lateral:system',
 'seamark:buoy_cardinal:category',
 'seamark:buoy_cardinal:colour',
 'seamark:buoy_cardinal:colour_pattern',
 'seamark:buoy_cardinal:shape',
 'seamark:buoy_isolated_danger:colour',
 'seamark:buoy_isolated_danger:colour_pattern',
 'seamark:buoy_isolated_danger:shape',
 'seamark:buoy_lateral:category',
 'seamark:buoy_lateral:colour',
 'seamark:buoy_lateral:shape',
 'seamark:buoy_lateral:system',
 'seamark:buoy_safe_water:colour',
 'seamark:buoy_safe_water:colour_pattern',
 'seamark:buoy_safe_water:shape',
 'seamark:buoy_special_purpose:colour',
 'seamark:buoy_special_purpose:shape',
 'seamark:construction',
 'seamark:fog_signal:category',
 'seamark:information',
 'seamark:landmark:category',
 'seamark:landmark:height',
 'seamark:light:1:character',
 'seamark:light:1:colour',
 'seamark:light:1:group',
 'seamark:light:1:height',
 'seamark:light:1:period',
 'seamark:light:1:radius',
 'seamark:light:1:range',
 'seamark:light:1:sector_end',
 'seamark:light:1:sector_start',
 'seamark:light:1:sequence',
 'seamark:light:category',
 'seamark:light:character',
 'seamark:light:colour',
 'seamark:light:group',
 'seamark:light:height',
 'seamark:light:multiple',
 'seamark:light:period',
 'seamark:light:range',
 'seamark:light:reference',
 'seamark:light:sequence',
 'seamark:light_major:height',
 'seamark:light_minor:height',
 'seamark:name',
 'seamark:radar_transponder:category',
 'seamark:radar_transponder:group',
 'seamark:radar_transponder:period',
 'seamark:rock:water_level',
 'seamark:small_craft_facility:category',
 'seamark:topmark:colour',
 'seamark:topmark:shape',
 'seamark:type',
 'seats',
 'security',
 'segregated',
 'self_service',
 'service',
 'service:bicycle:repair',
 'service:bicycle:retail',
 'service_times',
 'shelter',
 'shop',
 'shower',
 'sidewalk',
 'ski',
 'smoking',
 'smoothness',
 'snowmobile',
 'social_facility',
 'social_facility:for',
 'social_facility_for',
 'source',
 'source:highway',
 'source:maxspeed',
 'source:name',
 'source_ref',
 'sport',
 'sport:scuba_diving',
 'stars',
 'start_date',
 'step_count',
 'stop',
 'student',
 'substation',
 'supervised',
 'surface',
 'tactile_paving',
 'takeaway',
 'target',
 'taxi',
 'taxon',
 'tents',
 'toilets',
 'toilets:disposal',
 'toilets:position',
 'toll',
 'toll:bicycle',
 'toll:foot',
 'tourism',
 'tourist_bus',
 'tower:type',
 'tracktype',
 'traffic_calming',
 'traffic_sign',
 'trail_visibility',
 'train',
 'triangle',
 'trucks',
 'tunnel',
 'turn:lanes',
 'type',
 'usage',
 'vat',
 'vehicle',
 'vending',
 'via_ferrata_scale',
 'voltage',
 'water',
 'waterway',
 'website',
 'wetland',
 'wheelchair',
 'wheelchair:description',
 'width',
 'wifi',
 'wikidata',
 'wikipedia',
 'wires',
 'wood',
 'wreck:date_sunk',
 'wreck:depth',
 'year']

 """